# Generated by Django 3.2 on 2022-08-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.JSONField(verbose_name='Condition')),
                ('type', models.TextField(verbose_name=[('graham', 'graham'), ('kd tree', 'kd tree'), ('quickhull', 'quickhull')])),
            ],
        ),
    ]
