# Generated by Django 3.2 on 2022-08-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.TextField(choices=[('graham', 'graham'), ('kd tree', 'kd tree'), ('quickhull', 'quickhull')]),
        ),
    ]
