# Generated by Django 3.2 on 2022-09-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.TextField(default='Module1'),
            preserve_default=False,
        ),
    ]
