# Generated by Django 3.2 on 2022-09-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_module_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mark',
            constraint=models.UniqueConstraint(fields=('user', 'task'), name='core_mark_unique'),
        ),
    ]
